name: Build Images
on:
  push:
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
        - 'arm64'
        - 'x86-64'
        distro:
        - debian
        - fedora
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup mkosi
      uses: systemd/mkosi@v18
    - name: Summary
      run: |
        sudo mkosi --distribution=${{ matrix.distro }} summary
    - name: Build Image
      run: |
        sudo mkosi --root-password=toor --distribution=${{ matrix.distro }} --architecture=${{ matrix.architecture }}
    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.distro }}-image-${{ matrix.architecture }}
        path: ${{ matrix.distro }}.raw
        retention-days: 2
